# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

install! 'cocoapods',
:generate_multiple_pod_projects => true
use_frameworks!


pod 'cdebug', '~> 1.3'
pod 'FoundationExtension', :path => '../'

target 'FoundationExtensionTests' do
end

abstract_target 'Cocoa' do
  pod 'CocoaExtension', :path => '../'

  target 'CocoaExtensionTestApp' do
  end
  target 'CocoaExtensionTests' do
  end
end

abstract_target 'UIKit' do
  pod 'UIKitExtension', :path => '../'

  target 'UIKitExtensionTestApp' do
  end
  target 'UIKitExtensionTests' do
  end
end
