var hierarchy =
[
    [ "FSEventStream", "interfaceFSEventStream.html", null ],
    [ "<FSEventStreamDelegate>", "protocolFSEventStreamDelegate-p.html", null ],
    [ "NSAArray", "interfaceNSAArray.html", null ],
    [ "NSAClass", "interfaceNSAClass.html", null ],
    [ "NSADictionary", "interfaceNSADictionary.html", null ],
    [ "NSAMethod", "interfaceNSAMethod.html", null ],
    [ "NSAMutableArray", "interfaceNSAMutableArray.html", null ],
    [ "NSAMutableDictionary", "interfaceNSAMutableDictionary.html", [
      [ "NSAttributedStringAttributeDictionary", "interfaceNSAttributedStringAttributeDictionary.html", null ],
      [ "NSAttributedStringAttributeDictionary", "interfaceNSAttributedStringAttributeDictionary.html", null ]
    ] ],
    [ "NSAMutableOrderedDictionary", "interfaceNSAMutableOrderedDictionary.html", null ],
    [ "NSAMutableString", "interfaceNSAMutableString.html", null ],
    [ "NSAOrderedDictionary", "interfaceNSAOrderedDictionary.html", null ],
    [ "NSArray(Creations)", "categoryNSArray_07Creations_08.html", null ],
    [ "NSArray(Functional)", "categoryNSArray_07Functional_08.html", null ],
    [ "NSArray(NSNumber)", "categoryNSArray_07NSNumber_08.html", null ],
    [ "NSArray(NSURLRequest)", "categoryNSArray_07NSURLRequest_08.html", null ],
    [ "NSArray(Rearrange)", "categoryNSArray_07Rearrange_08.html", null ],
    [ "NSArray(Shortcuts)", "categoryNSArray_07Shortcuts_08.html", null ],
    [ "NSAString", "interfaceNSAString.html", null ],
    [ "NSATriple", "interfaceNSATriple.html", [
      [ "NSAMutableTriple", "interfaceNSAMutableTriple.html", null ]
    ] ],
    [ "NSAttributedString(Shortcuts)", "categoryNSAttributedString_07Shortcuts_08.html", null ],
    [ "NSATuple", "interfaceNSATuple.html", [
      [ "NSAMutableTuple", "interfaceNSAMutableTuple.html", null ]
    ] ],
    [ "NSAURLRequestHTTPBodyMultiPartFormPostFormatter", "interfaceNSAURLRequestHTTPBodyMultiPartFormPostFormatter.html", null ],
    [ "NSBundle(Shortcuts)", "categoryNSBundle_07Shortcuts_08.html", null ],
    [ "NSData(CommonCrypto)", "categoryNSData_07CommonCrypto_08.html", null ],
    [ "NSData(CommonCryptor)", "categoryNSData_07CommonCryptor_08.html", null ],
    [ "NSData(CommonCryptorString)", "categoryNSData_07CommonCryptorString_08.html", null ],
    [ "NSData(NSURL_deprecated)", "categoryNSData_07NSURL__deprecated_08.html", null ],
    [ "NSData(NSURLRequest)", "categoryNSData_07NSURLRequest_08.html", null ],
    [ "NSData(Serialization)", "categoryNSData_07Serialization_08.html", null ],
    [ "NSDate(Shortcuts)", "categoryNSDate_07Shortcuts_08.html", null ],
    [ "NSDecimalNumber(Description)", "categoryNSDecimalNumber_07Description_08.html", null ],
    [ "NSDictionary(Functional)", "categoryNSDictionary_07Functional_08.html", null ],
    [ "NSDictionary(NSData)", "categoryNSDictionary_07NSData_08.html", null ],
    [ "NSDictionary(NSURLRequest)", "categoryNSDictionary_07NSURLRequest_08.html", null ],
    [ "NSDictionary(Shortcuts)", "categoryNSDictionary_07Shortcuts_08.html", null ],
    [ "NSJSONSerialization(Shortcuts)", "categoryNSJSONSerialization_07Shortcuts_08.html", null ],
    [ "NSMutableArray(Functional)", "categoryNSMutableArray_07Functional_08.html", null ],
    [ "NSMutableArray(NSNumber)", "categoryNSMutableArray_07NSNumber_08.html", null ],
    [ "NSMutableAttributedString(AttributeProperties)", "categoryNSMutableAttributedString_07AttributeProperties_08.html", null ],
    [ "NSMutableDictionary(Functional)", "categoryNSMutableDictionary_07Functional_08.html", null ],
    [ "NSMutableURLRequest(HTTPMethod)", "categoryNSMutableURLRequest_07HTTPMethod_08.html", null ],
    [ "NSMutableURLRequest(NSAURLRequestHTTPBodyMultiPartFormPostFormatter)", "categoryNSMutableURLRequest_07NSAURLRequestHTTPBodyMultiPartFormPostFormatter_08.html", null ],
    [ "NSMutableURLRequest(Properties)", "categoryNSMutableURLRequest_07Properties_08.html", null ],
    [ "NSNumber(Description)", "categoryNSNumber_07Description_08.html", null ],
    [ "NSNumberFormatter(Shortcuts)", "categoryNSNumberFormatter_07Shortcuts_08.html", null ],
    [ "NSObject(NSAClass)", "categoryNSObject_07NSAClass_08.html", null ],
    [ "NSObject(ObjCRuntime)", "categoryNSObject_07ObjCRuntime_08.html", null ],
    [ "NSString(CommonCrypto)", "categoryNSString_07CommonCrypto_08.html", null ],
    [ "NSString(CommonCryptorString)", "categoryNSString_07CommonCryptorString_08.html", null ],
    [ "NSString(Creations)", "categoryNSString_07Creations_08.html", null ],
    [ "NSString(Evaluation)", "categoryNSString_07Evaluation_08.html", null ],
    [ "NSString(NSPathUtilities)", "categoryNSString_07NSPathUtilities_08.html", null ],
    [ "NSString(NSURL)", "categoryNSString_07NSURL_08.html", null ],
    [ "NSString(NSUTF8StringEncoding)", "categoryNSString_07NSUTF8StringEncoding_08.html", null ],
    [ "NSString(Shortcuts)", "categoryNSString_07Shortcuts_08.html", null ],
    [ "NSTextView(Placeholder)", "categoryNSTextView_07Placeholder_08.html", null ],
    [ "NSTimer(Delegate)", "categoryNSTimer_07Delegate_08.html", null ],
    [ "NSTimer(dispatch)", "categoryNSTimer_07dispatch_08.html", null ],
    [ "NSTimer(NSRunLoop)", "categoryNSTimer_07NSRunLoop_08.html", null ],
    [ "NSTimer(Shortcuts)", "categoryNSTimer_07Shortcuts_08.html", null ],
    [ "<NSTimerDelegate>", "protocolNSTimerDelegate-p.html", null ],
    [ "NSURL(Creations)", "categoryNSURL_07Creations_08.html", null ],
    [ "NSURLRequest(Creations_deprecated)", "categoryNSURLRequest_07Creations__deprecated_08.html", null ],
    [ "NSURLRequest(Properties)", "categoryNSURLRequest_07Properties_08.html", null ],
    [ "UIAColorComponents", "interfaceUIAColorComponents.html", null ],
    [ "UIADimmingView", "interfaceUIADimmingView.html", null ],
    [ "<UIADimmingViewDelegate>", "protocolUIADimmingViewDelegate-p.html", [
      [ "UIAResultDisplayController", "interfaceUIAResultDisplayController.html", null ]
    ] ],
    [ "UIAlertView(Shortcuts)", "categoryUIAlertView_07Shortcuts_08.html", null ],
    [ "UIApplication(Dump)", "categoryUIApplication_07Dump_08.html", null ],
    [ "UIApplication(Shortcuts)", "categoryUIApplication_07Shortcuts_08.html", null ],
    [ "<UIAResultDisplayDelegate>", "protocolUIAResultDisplayDelegate-p.html", null ],
    [ "UIATableViewCellCopyable", "interfaceUIATableViewCellCopyable.html", null ],
    [ "<UIATableViewCellCopyableDelegate>", "protocolUIATableViewCellCopyableDelegate-p.html", null ],
    [ "UIColor(Creations)", "categoryUIColor_07Creations_08.html", null ],
    [ "UIColor(HTMLColor)", "categoryUIColor_07HTMLColor_08.html", null ],
    [ "UIColor(Shortcuts)", "categoryUIColor_07Shortcuts_08.html", null ],
    [ "UIControl(Shortcuts)", "categoryUIControl_07Shortcuts_08.html", null ],
    [ "UIDevice(Shortcuts)", "categoryUIDevice_07Shortcuts_08.html", null ],
    [ "UIImage(UIGraphics)", "categoryUIImage_07UIGraphics_08.html", null ],
    [ "UIScrollView(Shortcuts)", "categoryUIScrollView_07Shortcuts_08.html", null ],
    [ "UITableViewCell(Shortcuts)", "categoryUITableViewCell_07Shortcuts_08.html", null ],
    [ "UIView(Animation)", "categoryUIView_07Animation_08.html", null ],
    [ "UIWebView(Shortcuts)", "categoryUIWebView_07Shortcuts_08.html", null ]
];