
from NSAttributedStringData import *

interface="""
/*!
 *  @brief Adds {name} attribute value to the characters in the specified range.
 *  @details Generated by {filename}
 */
- (void)addAttribute{Name}:({type}){name} range:(NSRange)range;
/*!
 *  @brief Removes {name} attribute from the characters in the specified range.
 *  @details Generated by {filename}
 */
- (void)removeAttribute{Name}FromRange:(NSRange)range;"""

for prop in props:
    if prop.name.endswith('Array'): continue
    print interface.format(
        type=prop.type,
        name=prop.name,
        Name=prop.Name,
        filename=__file__,
    )
