
from NSAttributedStringData import *

impl="""{availableheader}
//! Generated by {filename}
- (void)addAttribute{Name}:({type}){name} range:(NSRange)range {{ [self addAttribute:NS{Name}AttributeName value:{value} range:range]; }}
//! Generated by {filename}
- (void)removeAttribute{Name}FromRange:(NSRange)range {{ [self removeAttribute:NS{Name}AttributeName range:range]; }}
{availablefooter}"""

for prop in props:
    if prop.has_impl: continue
    print impl.format(
        type=prop.type,
        name=prop.name,
        value='[NSNumber numberWith{Number}:{name}]'.format(Number=prop.Number, name=prop.name) if prop.has_number else prop.name,
        Name=prop.Name,
        available=' ' + prop.available_mac if prop.available else '',
        availableheader=prop.available_header if prop.available else '',
        availablefooter='#endif' if prop.available else '',
        filename=__file__,
    )
